#!/usr/bin/env bash

#

# fetch genomes in the file ecoli_genomes.txt
# These are the directory names for genomes as
# per the directory format at the ncbi ftp website

for GENOME in $(cat ecoli_genomes.list) ; do 
	mkdir -p $GENOME
	sleep 2
	wget "ftp://ftp.ncbi.nlm.nih.gov/genomes/archive/old_refseq/Bacteria/$GENOME/*.fna"
	mv *.fna $GENOME
	# move plasmids to their own subdir
	cd $GENOME 
	mkdir plasmid
	for PLASMID in $(grep -il "plasmid" *.fna) ; do
		echo "moving plasmid: $PLASMID"  1>&2
		mv $PLASMID plasmid
	done
	cd ..
done
